<?= $this->doctype() ?>
<html lang="<?= $this->currentLocale() ?>" dir="<?= $this->localeDirection() ?>">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle($this->siteName())->setSeparator(' '.$this->siteSettings('site-title-separator').' ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->assetsPath('/img/favicon.ico')])
                ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css')
                ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css')
                ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css')
                ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/skins/square/blue.css')
                ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.5/css/AdminLTE.min.css')
                ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.5/css/skins/skin-black.min.css')
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js')
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js')
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js')
        ?>
    </head>
    <body class="hold-transition login-page">

        <div class="login-box">
            <?= $this->content ?>

            <footer class="text-center">
                <br>
                <p><?= sprintf($this->translate('Copyright &copy; %1$s by %2$s, All rights reserved','template/backend/adminlte'), date('Y'), $this->siteName()) ?></p>
            </footer>
        </div>
        <!-- /.login-box -->


        <?= $this->inlineScript() ?>

    </body>
</html>
