<?= $this->doctype() ?>
<html lang="<?= $this->currentLocale() ?>" dir="<?= $this->localeDirection() ?>">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle($this->siteName())->setSeparator(' '.$this->siteSettings('site-title-separator').' ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->assetsPath('/img/favicon.ico')])
                ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css')
                ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css')
                ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css')
                ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/skins/flat/blue.css')
                ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.5/css/AdminLTE.min.css')
                ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.5/css/skins/skin-blue.min.css')
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js')
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js')
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js')
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/fastclick/1.0.6/fastclick.min.js')
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/jQuery-slimScroll/1.3.8/jquery.slimscroll.min.js')
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.3.5/js/app.min.js')
        ?>
    </head>
    <body class="hold-transition skin-blue sidebar-mini">

        <div class="wrapper">

          <?= $this->partial('layout/partials/header') ?>

          <!-- Left side column. contains the logo and sidebar -->
          <?= $this->partial('layout/partials/sidebar') ?>


          <!-- Content Wrapper. Contains page content -->
          <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
              <h1><?= $this->pageTitle() ?></h1>

              <?= $this->navigation('breadcrumb')->breadcrumbs()->setPartial('layout/partials/breadcrumb')->setMinDepth(0) ?>
            </section>

            <!-- Main content -->
            <section class="content">
                <?= $this->content ?>
            </section>
            <!-- /.content -->
          </div>
          <!-- /.content-wrapper -->

          <footer class="main-footer">
            <div class="pull-right hidden-xs">
              <b><?= $this->translate('Version', 'template/backend/adminlte') ?></b> <?= Application\Module::VERSION ?>
            </div>
            <p><?= sprintf($this->translate('Copyright &copy; %1$s by %2$s, All rights reserved','template/backend/adminlte'), date('Y'), $this->siteName()) ?></p>
          </footer>

          <?php if ($this->templateSettings('show-control-sidebar') == true) : ?>
          <!-- Control Sidebar -->
          <?= $this->partial('layout/partials/control-sidebar') ?>
          <!-- /.control-sidebar -->
          <!-- Add the sidebar's background. This div must be placed
               immediately after the control sidebar -->
          <div class="control-sidebar-bg"></div>
        <?php endif; ?>

        </div>
        <!-- ./wrapper -->

        <?= $this->inlineScript() ?>

    </body>
</html>
