<!-- Language Switcher -->
<li class="dropdown language-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-language"></i>
        <span class="label label-warning"><?= $this->currentLocale() ?></span>
    </a>
    <ul class="dropdown-menu">
        <?php foreach ($this->localesList() as $locale) :
            $route = $this->currentRoute() ?: 'admin/dashboard';
            $routeParams = $this->currentRouteParams() ?: [];
        ?>
        <li>
            <a href="<?= $this->localeUrl($route, $routeParams, $locale['locale']) ?>">
                <img src="<?= $this->basePath('assets/common/img/flags/'.$locale['region_code'].'.png') ?>" />
                <?= $locale['name'] ?>
            </a>
        </li>
        <?php endforeach; ?>
    </ul>
</li>