<!-- Language Switcher -->
<li class="dropdown language-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-language"></i>
        <span class="label label-warning"><?= $this->currentLocale() ?></span>
    </a>
    <ul class="dropdown-menu">
        <?php foreach ($this->localesList() as $locale) : ?>
        <li><a href="<?= $this->localeUrl($this->currentRoute(), [], $locale['locale']) ?>"><?= $locale['name'] ?></a></li>
        <?php endforeach; ?>
    </ul>
</li>