<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">

            <div class="box-header with-border">
                <h3 class="box-title"><?= $this->pageTitle() ?></h3>
            </div>

            <div class="box-body">
                <table id="grid-panel" data-order="[[0, &quot;asc&quot;]]" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <?php foreach ($grid->columns() as $column) : ?>
                            <th
                                data-orderable="<?= isset($column['orderable']) && $column['orderable'] == false ? 'false' : 'true' ?>"
                                data-searchable="<?= isset($column['searchable']) && $column['searchable'] == false ? 'false' : 'true' ?>"
                                >
                                <?= isset($column['label']) ? $column['label'] : '' ?>
                            </th>
                            <?php endforeach; ?>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($grid->data() as $item) : ?>
                        <tr>
                            <?php foreach ($grid->columns() as $column) : ?>
                            <td><?php
                                if (isset($column['field'], $item[$column['field']]))
                                {
                                    echo $item[$column['field']];
                                }
                                elseif (isset($column['actions']))
                                {
                                    ?>
                                <div class="btn-group">
                                    <?php foreach ($column['actions'] as $aItem) : ?>
                                    <a class="btn btn-flat bg-<?= $aItem['color'] ?>" href="<?= $aItem['link']($item) ?>"><i class="<?= $aItem['icon'] ?>"></i> <span class="hidden-xs"><?= $this->translate($aItem['label']) ?></span></a>
                                    <?php endforeach; ?>
                                </div>
                                    <?php
                                }
                            ?></td>
                            <?php endforeach; ?>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>


<?php

$this->inlineScript()->appendScript($this->partial('layout/pages/js/list'));