<li class="active treeview">
  <a href="#">
    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
    <span class="pull-right-container">
      <i class="fa fa-angle-left pull-right"></i>
    </span>
  </a>
  <ul class="treeview-menu">
    <li><a href="#"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>
    <li class="active"><a href="#"><i class="fa fa-circle-o"></i> Dashboard v2</a></li>
  </ul>
</li>
