<?php

$field->setAttribute('class','form-control');

$addon_prefix = $field->getOption('addon-prefix');
$addon_suffix = $field->getOption('addon-suffix');

$input_size = $field->getOption('input-size');

?>

<?php if ($input_size) : ?>
<div class="col-sm-<?= $input_size ?>">
<?php endif; ?>

    <?php if ($addon_prefix || $addon_suffix) : ?>
    <div class="input-group">
    <?php endif; ?>

        <?php if ($addon_prefix) : ?>
        <span class="input-group-addon"><?= $addon_prefix ?></span>
        <?php endif; ?>


            <?= $this->formElement($field) ?>


        <?php if ($addon_suffix) : ?>
        <span class="input-group-addon"><?= $addon_suffix ?></span>
        <?php endif; ?>

    <?php if ($addon_prefix || $addon_suffix) : ?>
    </div>
    <?php endif; ?>

<?php if ($input_size) : ?>
</div>
<?php endif; ?>