<?php

$value_options = $field->getValueOptions();

foreach ($value_options as $value_option_key => $value_option) :

?>

<div class="radio<?= $field->getOption('inline') ? '-inline' : '' ?>">
    <label>
        <input type="radio" name="<?= $field->getName() ?>" value="<?= $value_option_key ?>" <?= $field->getValue() == $value_option_key ? 'checked="checked"' : '' ?> /> <?= $value_option ?>
    </label>
</div>

<?php endforeach;